### ISSUE TITLE
isDev undefined

### ISSUE THREAD

**Issue by ais-one** [wemake-services/nuxt-imagemin#1]
process.isDev is undefined, so how should be detect if running on dev environment? use NODE_ENV instead?

**Comment by sobolevn** [comment]
@ais-one hm, very strange. I got this working for me.

What's your setup and `nuxt` version?
I will revisit documentation to find the right solution.

Pull requests are warmly welcomed!

**Comment by ais-one** [comment]
Hi,

version is Nuxt 1.4.0

**Comment by sobolevn** [comment]
Thanks for reporting.
Reference: https://nuxtjs.org/guide/modules/

New version `0.1.2` is released.

Also, @ais-one check our application template: https://github.com/wemake-services/wemake-vue-template

**Comment by ais-one** [comment]
thanks it is working now, yes will have a look at the template, looks interesting
