### ISSUE TITLE
Asking for a working example :)

### ISSUE THREAD

**Issue by gaisinskii** [wemake-services/nuxt-imagemin#29]
Greetings!

If it is possible can you provide a working example of this plugin. For some reason it doesn't work for me and i am a bit confused because the installation and usage process is pretty straight forward.

I've tried many different options, but still when i do `npm run build`, nuxt will scream at me that some of the images are over 300kB.

Thanks in advance!

Best regards,
Andy

**Comment by sobolevn** [comment]
Sure, I have plans to work on this plugin. Currently it misses some major features like good docs, and examples.

We are using this plugin in our `nuxt` template: https://github.com/wemake-services/wemake-vue-template

Here's how it is configured: https://github.com/wemake-services/wemake-vue-template/blob/master/template/nuxt.config.js#L52

And that's how it is installed: https://github.com/wemake-services/wemake-vue-template/blob/master/template/package.json#L56

Feel free to ask any questions if that still not working.

**Comment by gaisinskii** [comment]
I've tried to recreate this problem in a test project using this template - https://github.com/nuxt-community/starter-template Its still the same for me, when i get back home i will do it again and probably will make a repo.

Thanks for your response!

**Comment by gaisinskii** [comment]
And I am back again. Github repo is below.

Here is my route:

1. Have created a nuxt project using https://github.com/nuxt-community/create-nuxt-app
1.1 The project setup is : 


     ![](https://puu.sh/B6oWr/9b9e912764.png)
2. Have taken a random png image from google and put it in `~/assets` 
Image link is -https://nirklars.files.wordpress.com/2015/02/extrasolar_comet_by_nirklars-d8epalq.png

3. My html in `pages/index.vue` : 
```
<template>
  <section class="container">
    <img src="~/assets/test.png" alt="">
  </section>
</template>
```

4. Now, if i do `npm run build` **without** nuxt-imagemin we will get this - as expected:


    ![](https://puu.sh/B6pKZ/874aa64cd3.png)


5. Installing nuxt-imagemin with `npm install --save nuxt-imagemin` installs like a charm, no errors at all
5.1 And configure it like this in `nuxt.config.js`:
      ```
      modules: [
        // Doc: https://github.com/nuxt-community/axios-module#usage
        '@nuxtjs/axios',
        'nuxt-imagemin',
    ],
    ````
6. Running `npm run build` again and getting this:

    ![](https://puu.sh/B6q5l/5b8ec18faa.png)

**Here is the github repo - https://github.com/andy-noir/nuxt-imagemin-test**

Thanks in advance for spending your time and reading all that text :)

Best regards,
Andy

**EDIT:** Forgot to mention that the first time i have used your plugin, i have been using Ubuntu and this repo was made on Windows (if it matters ofc)

**Comment by sobolevn** [comment]
Oh, I see what happened. This is just a warning that some asset is bigger than a predefined limit.

I does not actually affect your app.

@andy-noir can you please verify that given `png` image is compressed? 
To do so, you need to check the size of the original image from `assets` and the result image from `dist/img`.

If it works, we can close the issue.

**Comment by gaisinskii** [comment]
@sobolevn After i do `npm run generate` it is almost the same (was 993kB, now 992kB) and i still get that warning.

**Comment by sobolevn** [comment]
So, maybe it is already compressed. 
@andy-noir thank you very much for bringing this up.

If you really want to get reed of the warning: https://github.com/webpack/webpack/issues/3486#issuecomment-267257851

There's nothing I can do from my side.
