### ISSUE TITLE
cannot add to my project and gulp-util is deprecated 

### ISSUE THREAD

**Issue by arslanyunus** [wemake-services/nuxt-imagemin#30]
Hi,

I tried to add this package to my project. it gives warning and throws an error saying; 

` yarn add nuxt-imagemin          
yarn add v0.27.5
[1/4] Resolving packages...
warning nuxt-imagemin > imagemin-webpack-plugin > imagemin-gifsicle > gifsicle > bin-build > download > gulp-decompress > gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
[2/4] Fetching packages...
error eslint@5.1.0: The engine "node" is incompatible with this module. Expected version "^6.14.0 || ^8.10.0 || >=9.10.0".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
`

I don't understand why i cannot add this. Is this related to deprecated package gulp-util which is mentioned on url shown on warning, or is it something else?

Regards,
Yunus

**Comment by arslanyunus** [comment]
i guess its all because node version is out-dated. updated node to latest version. its all good now.

sorry to bother you with this.

**Comment by sobolevn** [comment]
@arslanyunus thanks for posting the solution! 

Glad it worked.
