### ISSUE TITLE
WebP support

### ISSUE THREAD

**Issue by andrevandal** [wemake-services/nuxt-imagemin#67]
Hi.

Is it possible to add support for the WebP format?
There is a [library for the "imagemin"](https://github.com/imagemin/imagemin-webp) that might help.

Thanks.

**Comment by sobolevn** [comment]
Sure! Can you please send a PR?

**Comment by ricardogobbosouza** [comment]
@derevandal no need a PR, just right configuration..

**nuxt.config.js**
```js
import imageminWebp from 'imagemin-webp'

module.exports = {
  ....
  modules: [
    ['nuxt-imagemin', {
      plugins: [
        imageminWebp({quality: 50})
      ]
    }]
  ]
  ...
}
```

**Comment by sobolevn** [comment]
@derevandal please, verify that @ricardogobbosouza's solution works. And I will close this issue.

**Comment by andrevandal** [comment]
@sobolevn can you close and accept my pr to document this in readme
